export const API_URL = "https://admin.models.ai4bharat.org";
export const LANGUAGE_CODE_NAMES = {
  gom: "Konkani",
  mai: "Maithili",
  kn: "Kannada",
  ne: "Nepali",
  ta: "Tamil",
  ks: "Kashmiri",
  pa: "Punjabi",
  sat: "Santali",
  en: "English",
  brx: "Bodo",
  sa: "Sanskrit",
  doi: "Dogri",
  te: "Telugu",
  ur: "Urdu",
  as: "Assamese",
  sd: "Sindhi",
  hi: "Hindi",
  or: "Odia",
  ml: "Malayalam",
  gu: "Gujarati",
  bn: "Bengali",
  mr: "Marathi",
  mni: "Meitei (Manipuri)",
  raj: "Rajasthani",
  si: "Sinhala",
};

export const imagePrefix = process.env.BASE_PATH || "";
