# Generated by Django 5.1 on 2025-06-23 06:34

import areas.models
import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('published_on', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to=areas.models.image_directory_path)),
                ('related_link', models.URLField(blank=True, max_length=500, null=True)),
                ('markdown_content', models.TextField(blank=True, null=True)),
                ('cover_image', models.JSONField(blank=True, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('affiliations', models.JSONField(blank=True, null=True)),
                ('publication_links', models.JSONField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, null=True)),
                ('team', models.JSONField(blank=True, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
