# Generated by Django 4.2.17 on 2025-06-24 05:58

import areas.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                (
                    "paper_award",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("ASR", "Asr"),
                            ("NMT", "Nmt"),
                            ("TTS", "Tts"),
                            ("XLIT", "Xlit"),
                            ("LLM", "Llm"),
                            ("SLR", "Slr"),
                            ("NLP", "Nlp"),
                            ("NLG", "Nlg"),
                            ("NLU/PEFT", "Nlu"),
                        ],
                        max_length=10,
                    ),
                ),
                ("published_on", models.DateField(default=datetime.date.today)),
                ("conference", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField()),
                ("paper_link", models.URLField(max_length=500)),
                (
                    "website_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("github_link", models.URLField(blank=True, max_length=500, null=True)),
                ("hf_link", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("license_name", models.CharField(max_length=500)),
                ("liense_url", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                (
                    "paper_award",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("ASR", "Asr"),
                            ("NMT", "Nmt"),
                            ("TTS", "Tts"),
                            ("XLIT", "Xlit"),
                            ("LLM", "Llm"),
                            ("SLR", "Slr"),
                            ("NLP", "Nlp"),
                            ("NLG", "Nlg"),
                            ("NLU/PEFT", "Nlu"),
                        ],
                        max_length=10,
                    ),
                ),
                ("published_on", models.DateField(default=datetime.date.today)),
                ("latest", models.BooleanField(default=False)),
                ("conference", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField()),
                ("paper_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "website_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("github_link", models.URLField(blank=True, max_length=500, null=True)),
                ("colab_link", models.URLField(blank=True, max_length=500, null=True)),
                ("hf_link", models.URLField(blank=True, max_length=500, null=True)),
                ("service_id", models.CharField(blank=True, max_length=500, null=True)),
                ("installation_steps_json", models.JSONField(blank=True, null=True)),
                ("usage_steps_json", models.JSONField(blank=True, null=True)),
                ("testimonials_json", models.JSONField(blank=True, null=True)),
                (
                    "license",
                    models.ManyToManyField(blank=True, null=True, to="areas.license"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("serviceId", models.CharField(max_length=500)),
                ("task", models.CharField(max_length=500)),
                ("postedOn", models.DateField(default=datetime.date.today)),
                ("modelInput", models.TextField()),
                ("modelResponse", models.TextField()),
                ("liked", models.BooleanField(default=False)),
                ("comment", models.TextField()),
                (
                    "sourceLanguage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "targetLanguage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("domain", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("published_on", models.DateField(default=datetime.date.today)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=areas.models.image_directory_path,
                    ),
                ),
                (
                    "related_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("markdown_content", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("main_video_hyperlink", models.URLField(max_length=500)),
                ("hyperlink_buttons_json", models.JSONField()),
                ("release_timeline_json", models.JSONField()),
                ("feature_cards_json", models.JSONField()),
                ("contributor_cards_json", models.JSONField()),
                ("installation_steps_json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "dataset",
                    models.ManyToManyField(blank=True, null=True, to="areas.dataset"),
                ),
                (
                    "model",
                    models.ManyToManyField(blank=True, null=True, to="areas.model"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="license",
            field=models.ManyToManyField(blank=True, null=True, to="areas.license"),
        ),
    ]
